### ISSUE TITLE
Updated visual design for Dark Vision web app

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/openwhisk-darkvisionapp#23]
How can the Dark Vision web app can be improved to show the new insights coming from the audio stream?

Capabilities of Dark Vision V1 web user interface:
- [x] Upload video
- [x] Upload image
- [x] View list of uploaded videos
- [x] View list of uploaded images
- [x] View results for a video
 - [x] View individual images extracted from the video
 - [x] View summary results
 - [x] View individual results for each image
 - [x] Relaunch an analysis of the video (extract + image process)
 - [x] Restart the analysis of all images (image process only)
- [x] View results for an image
- [x] Link to GitHub source code
- [x] Link to Youtube video

**Comment by Austinauth** [comment]
Here's V1 of the Web Interface. Visual HiFis are still needed.

You can also access the [Invision prototype here](https://invis.io/4JAKRPCVM).

##### Landing 
![01-landing_populated](https://cloud.githubusercontent.com/assets/6994218/23268285/d5ab5dd2-f9b2-11e6-98d6-e04792b752f1.jpg)

##### Landing - Upload
![02-landing_upload](https://cloud.githubusercontent.com/assets/6994218/23268293/e2ff28d8-f9b2-11e6-9be6-2f3cc2774962.jpg)

##### Landing - Processing
(Will update with Processing Module that works on all screens)
![03-landing_processing](https://cloud.githubusercontent.com/assets/6994218/23268318/f719f794-f9b2-11e6-8d04-cc2d18fa17ef.png)

##### Landing - Video Filter
![04-landing_video-filter](https://cloud.githubusercontent.com/assets/6994218/23268366/1d3498da-f9b3-11e6-97d1-3848aa755385.jpg)

##### Landing - Image Filter
![05-image-filter](https://cloud.githubusercontent.com/assets/6994218/23268374/2692a7dc-f9b3-11e6-9116-a844020b70cb.jpg)

##### Video Detail - Overview
![06-detail_video-overview](https://cloud.githubusercontent.com/assets/6994218/23268401/3c896b52-f9b3-11e6-9010-8bb89ca62f48.jpg)

##### Video Detail - Frame Overview 
![07-detail_frame-overview copy](https://cloud.githubusercontent.com/assets/6994218/23268420/49fd88e0-f9b3-11e6-8839-82759f357ca6.jpg)
