### ISSUE TITLE
[Visual Bug] Header Icon Sizing & Spacing

### ISSUE THREAD

**Issue by Austinauth** [IBM-Bluemix/openwhisk-darkvisionapp#29]
## Problem
![screen shot 2017-03-06 at 11 27 46 am](https://cloud.githubusercontent.com/assets/6994218/23621357/fb400678-025f-11e7-83d7-b97d8cda6318.png)

* The icons are slightly larger than needed, `32px` x `32px`.
* Spacing between icons is too large, `40px`.

## Solution
![screen shot 2017-03-06 at 11 28 50 am](https://cloud.githubusercontent.com/assets/6994218/23621468/7cac42da-0260-11e7-93bb-df31336f64bb.png)
* Icons should be a max of `28px` by `28px`.
* Icons should have a left margin of `20px` (see below).
![spacing](https://cloud.githubusercontent.com/assets/6994218/23621580/f9d0a04e-0260-11e7-9e20-2dfdc805176d.jpg)
* The _Cloud Upload_ icon should be `22px` x `16px` with a left margin of `8px`(see below). **This is the only icon that should have different dimensions.**

![screen shot 2017-03-06 at 11 38 44 am](https://cloud.githubusercontent.com/assets/6994218/23621759/941eea48-0261-11e7-9fe0-736254b0a044.png)

**Comment by Austinauth** [comment]
Spacing and sizing solved with PR: https://github.com/IBM-Bluemix/openwhisk-darkvisionapp/pull/32

We still need to adjust the Cloud Upload icon size.

**Comment by l2fprod** [comment]
adjusted cloud upload size
