### ISSUE TITLE
better logging and diagnostic

### ISSUE THREAD

**Issue by aslom** [IBM-Bluemix/openwhisk-darkvisionapp#3]
there should be better logging to track what is going during deployment and execution

for deploying print more what is happening so more help when it fails 

for operations print more in logs - for example currently my demo deployment processed two videos but stopped after that with no error i could find ...

**Comment by l2fprod** [comment]
hi @aslom, thanks for the feedback. Do you have specific log statements you'd like to see or were missing (in which part of the source code)? Don't hesitate to send a pull request :)
