### ISSUE TITLE
[Visual Bug]Filter Spacing

### ISSUE THREAD

**Issue by Austinauth** [IBM-Bluemix/openwhisk-darkvisionapp#42]
## Problem
![screen shot 2017-03-13 at 9 39 57 am](https://cloud.githubusercontent.com/assets/6994218/23859297/2a298506-07d1-11e7-80c2-6ce4c2b49aca.png)

Spacing between filter components is is incorrect.

## Solution
![screen shot 2017-03-13 at 9 47 21 am](https://cloud.githubusercontent.com/assets/6994218/23859618/35bd7958-07d2-11e7-89b9-ab79051fd49a.png)

**Comment by l2fprod** [comment]
@Austinauth the margin you show does not consider the hover state of the buttons:

![image](https://cloud.githubusercontent.com/assets/12746550/23944053/c8404a26-0971-11e7-8f51-75b35f411015.png)

Given this hover state, what should be the margin, padding, min-size?

I made changes you can look at to see if it matches what you had in mind.
