### ISSUE TITLE
After first deploy, video frames are processed but not the audio

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/openwhisk-darkvisionapp#51]
Seems to come from an issue registering the Speech to Text callback in the toolchain.

The call to register fails with an error 406. It could be due to a concurrency issue where the speechtotext web action is not yet exposed by OpenWhisk when we try to call it during registration.

A re-run of the pipeline usually solves the issue.

```
{"code":400,"code_description":"Bad Request","error":"unable to register callback url 'https://openwhisk.ng.bluemix.net/api/v1/experimental/web/user_space/vision/speechtotext.http', callback server responded with status code 406"}
```

**Comment by luiscosio** [comment]
After a re-run of the pipeline, I keep experiencing the same issue. Is there anyway I can fix this?

**Comment by luiscosio** [comment]
@l2fprod I'm pretty sure is related to this:

http://stackoverflow.com/questions/38538734/speech-recognition-callback-registration-fails

**Comment by l2fprod** [comment]
@luiscosio 

I have the feeling something as changed in Watson STT. There was a bug where they were sending application/json as content type but expecting text. It seems they are now sending "Accept: text/plain". However the OpenWhisk action is still returning application/json and OpenWhisk does not like the mismatch. I'm looking into it now.

**Comment by l2fprod** [comment]
@luiscosio 

The Watson STT "Accept" header changed from application/json to text/plain. This explains the 406.  This commit https://github.com/IBM-Bluemix/openwhisk-darkvisionapp/commit/a95478ef667b429f3dc4397355203a595a603511 fixes this.

**Comment by kmalave** [comment]
I'm getting this same issue now.  It looks like the action is being called by STT but STT doesn't like the reply.  Here is what the vision/speechtotext action reports in the logs:
{
    "headers": {
        "Content-Type": "text/plain"
    },
    "body": "uNuCKwTrYjbdKM3V"
}Logs:

    [OK] args.__ow_method= get  args.challenge_string= uNuCKwTrYjbdKM3V
    Replying to a challenge request from Watson Speech to Text...
    [OK] Challenge accepted!
I wonder if the encryption changed?  I will look further.
