### ISSUE TITLE
Support youtube video

### ISSUE THREAD

**Issue by bgbraga** [IBM-Bluemix/openwhisk-darkvisionapp#62]
I see that we have to upload a mp4 file.
But it will really nice if we could put a youtube link and openwhisk do the job from youtube.

**Comment by l2fprod** [comment]
this would make a good addition but it goes beyond the app scope. If you implement this one aspect to look at is the download, if the download from youtube + upload to Dark Vision takes more than 5min you will not be able to run this in an OpenWhisk action - they are limited to 5min.
