### ISSUE TITLE
After the first day it does not work!

### ISSUE THREAD

**Issue by mertmgokce** [IBM-Bluemix/openwhisk-darkvisionapp#63]
Hi,

I applied on my Bluemix account this example with instructions of deploying Dark Vision automatically. It is work and I upload 3 videos and 5 images this is prefect. The next day after deploying, a problem occurred. I tried to upload video or images, it only wait for processing and it does not give any result for videos or images. Briefly, after the first day it does not work. Is there any limitations or any bug.

This is screen shot of the error.
![dark_vision_error](https://user-images.githubusercontent.com/26893601/27026634-16cef558-4f67-11e7-9381-cd45855361a9.PNG)

**Comment by l2fprod** [comment]
@mertmgokce:

1/ Click on the video and use the menu on the top right to "Relaunch Video Analysis"
2/ Look at the OpenWhisk activation logs. Check the "extractor" action logs for any issue.

**Comment by mertmgokce** [comment]
I tried this steps again and again.

There is no log for "extractor" after the "Relaunch Video Analysis". 
There are logs only for 08/06/2017. This date is the first day I built the app. It looks like the connection was broken on the second day.

**Comment by l2fprod** [comment]
@mertmgokce 

what activations do you see after pressing Relaunch Video Analysis?

Note that I'm talking about the OpenWhisk logs, not the Cloud Foundry app logs. You can look at activations in OpenWhisk console (https://console.bluemix.net/openwhisk/dashboard)
or with "wsk activation list"

**Comment by mertmgokce** [comment]
I know I am looking same logs. 
There are no reactions on OpenWhisk logs after pressing Relaunch Video Analysis.

I will redeploy this application but I want to understand why did app run only first day?

**Comment by l2fprod** [comment]
@mertmgokce 

The trigger monitoring the Cloudant database may be broken for an unknown reason. Does the same thing happen for images today?

Make sure the actions still exist in OpenWhisk - to be on the safe side.

If you deployed with the toolchain, go in the toolchain and press the run button to redeploy. This will reinstall the OpenWhisk actions and triggers. Look at the toolchain log for any error.

**Comment by mertmgokce** [comment]
I checked it for cloudant-trigger but didn't have any error about that. The same is true for images.

I applied your advice and used the run button to redeploy. Now, application and all actions are working perfect. In addition, I will wait one day and I am following all logs.

Thanks.

**Comment by l2fprod** [comment]
@mertmgokce 

any news?

**Comment by mertmgokce** [comment]
Sorry for the delay,

I checked again and again and it is working. Today, I upload a long video to try it is working perfect.

Thank you very much for your relevance.

**Comment by l2fprod** [comment]
let's close it then. My guess is that something went wrong on the Cloudant side and the trigger was no longer received change updates from Cloudant.
