### ISSUE TITLE
Enable tiling of images as an option, then classify each tile with a custom classifier

### ISSUE THREAD

**Issue by andrewyuau** [IBM-Bluemix/openwhisk-darkvisionapp#66]
This is an enhancement request. This is similar to https://github.com/IBM-Cloud/Visual-Recognition-Tile-Localization. The use case is that a user uploads a video, the app will split it into frames (already supported in openwhisk-darkvisionapp), then split each frame to multiple tiles and classify each tile with a custom classifier.

**Comment by l2fprod** [comment]
Although this usecase can be of value for a product and could be implemented with Dark Vision, it is not within the scope of Dark Vision to deliver such capabilities. Dark Vision is meant as a technology demo for Cloud Functions and several Watson services.
