### ISSUE TITLE
[eu-de] Audio processing is not taking place on video - problem in deploy chain

### ISSUE THREAD

**Issue by EamonIvri** [IBM-Bluemix/openwhisk-darkvisionapp#73]
When a video with audio is uploaded the video processes fine but the audio doesn't seem to at all. Having checked the logs from the toolchain deploy I believe the issue to be here:

<img width="813" alt="screen shot 2018-06-05 at 14 44 22" src="https://user-images.githubusercontent.com/32772872/40980503-7006f7b4-68d0-11e8-92c4-46ceb53d40a5.png">

**Comment by l2fprod** [comment]
I could reproduce the issue when deploying to Germany - will raise it to the Speech to Text team

**Comment by l2fprod** [comment]
limiting to us-south
