### ISSUE TITLE
Any option for text?

### ISSUE THREAD

**Issue by MsFakhra** [IBM-Bluemix/openwhisk-darkvisionapp#77]
Is there any option on IBM Watson for text extraction and analysis like this one?

**Comment by l2fprod** [comment]
Dark Vision uses Watson Natural Language Understanding (https://www.ibm.com/watson/services/natural-language-understanding/) to process the video transcript.

Please direct this type of questions to Stackoverflow https://stackoverflow.com/questions/tagged/ibm-watson
